In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
"""
The standard library offers a rich selection of sequence types implemented in C:
Container sequences:
    list, tuple, and collections.deque can hold items of different types
Flat sequences
    str, bytes, bytearray, memoryview, and array.array hold items of one type
    
Container sequences hold references to the objects they contain, which may be of any
type, while flat sequences physically store the value of each item within its own memory
space, and not as distinct objects. Thus, flat sequences are more compact, but they are
limited to holding primitive values like characters, bytes, and numbers

Mutable sequences
    list, bytearray, array.array, collections.deque, and memoryview
Immutable sequences
    tuple, str, and bytes
"""


'\nThe standard library offers a rich selection of sequence types implemented in C:\nContainer sequences:\n    list, tuple, and collections.deque can hold items of different types\nFlat sequences\n    str, bytes, bytearray, memoryview, and array.array hold items of one type\n    \nContainer sequences hold references to the objects they contain, which may be of any\ntype, while flat sequences physically store the value of each item within its own memory\nspace, and not as distinct objects. Thus, flat sequences are more compact, but they are\nlimited to holding primitive values like characters, bytes, and numbers\n\nMutable sequences\n    list, bytearray, array.array, collections.deque, and memoryview\nImmutable sequences\n    tuple, str, and bytes\n'

In [5]:
# list comprehensions and generator expressions
"""
For brevity, many Python programmers refer to list comprehensions as listcomps, and generator expressions as genexps.
I will use these words as well.
listcomps: more readable and often faster
a listcomp is meant to do one thing only: to build a new list
keep it short
"""
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

codes1 = [ord(symbol) for symbol in symbols]
codes1

'\nFor brevity, many Python programmers refer to list comprehensions as listcomps, and generator expressions as genexps.\nI will use these words as well.\nlistcomps: more readable and often faster \n'

[36, 162, 163, 165, 8364, 164]

[36, 162, 163, 165, 8364, 164]

In [6]:
# listcomps versus map and filter
# listcomps do everything the map and filter functions do
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

[162, 163, 165, 8364, 164]

In [7]:
# Cartesian Products
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts
# equals:
for color in colors:
    for size in sizes:
        print((color, size))

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [9]:
# generator expression
"""
a genexp saves memory because it yields items one by one using the iterator
protocol instead of building a whole list just to feed another constructor

enclosed in parentheses rather than brackets
"""
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)

import array
array.array('I', (ord(symbol) for symbol in symbols))

'\na genexp saves memory because it yields items one by one using the iterator\nprotocol instead of building a whole list just to feed another constructor\n\nenclosed in parentheses rather than brackets\n'

(36, 162, 163, 165, 8364, 164)

array('I', [36, 162, 163, 165, 8364, 164])

In [2]:
# tuples are not just immutable lists
"""
tuples do double duty: they can be used as immutable lists and also as records with no field name
Tuples hold records: each item in the tuple holds the data for one field and the position of the item gives its meaning.
"""
# examples of tuple used as records
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]


'\ntuples do double duty: they can be used as immutable lists and also as records with no field name\nTuples hold records: each item in the tuple holds the data for one field and the position of the item gives its meaning.\n'

In [7]:
# tuple unpacking
# tuple unpacking works with any iterable object The only requirement
# is that the iterable yields exactly one item per variable in the receiving tuple
# parallel assignment
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
latitude
longitude

# swap the values of variables without using a temporary variable
a = 2
b = 3
a, b = b, a
a
b

# Another example of tuple unpacking is prefixing an argument with a star when calling a function
divmod(20, 8)
t = (20, 8)
divmod(*t)
quotient, remainder = divmod(*t)
quotient, remainder

# placeholder _

# using * to grab excess items
a, b, *rest = range(5)
a, b, rest
a, *body, c, d = range(5)
a, body, c, d

# nested tuple: (a, (b, c), d)

33.9425

-118.408056

3

2

(2, 4)

(2, 4)

(2, 4)

(0, 1, [2, 3, 4])

(0, [1, 2], 3, 4)

In [10]:
# named tuples
"""
Instances of a class that you build with namedtuple take exactly the same  amount  of  memory  as  
tuples  because  the  field  names  are stored in the class. They use less memory than a regular 
object because they don’t store attributes in a per-instance     dict    .
"""
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo
tokyo.population
tokyo.coordinates
tokyo[1]    # access the fields by name or position

"""
A named tuple type has a few attributes in addition to those inherited from tuple.
Example 2-10 shows the most useful: the _fields class attribute, the class method
_make(iterable), and the _asdict() instance method.
"""
City._fields
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()
for key, value in delhi._asdict().items():
    print(key + ':', value)


'\nInstances of a class that you build with namedtuple take exactly the same  amount  of  memory  as  \ntuples  because  the  field  names  are stored in the class. They use less memory than a regular \nobject because they don’t store attributes in a per-instance     dict    .\n'

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

36.933

(35.689722, 139.691667)

'JP'

'\nA named tuple type has a few attributes in addition to those inherited from tuple.\nExample 2-10 shows the most useful: the _fields class attribute, the class method\n_make(iterable), and the _asdict() instance method.\n'

('name', 'country', 'population', 'coordinates')

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', LatLong(lat=28.613889, long=77.208889))])

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


In [4]:
# Slicing
"""
why slices and range exclude the last item, work well with the zero-based indexing
1. it's easy to see the length, range(3) and my_list[:3] both produce three items
2. it's easy to compute the length of a slice or range when start and stop are given: just stop - start
3. It’s easy to split a sequence in two parts at any index x, without overlapping: simply get my_list[:x] and my_list[x:].
"""
l = [10, 20, 30, 40, 50, 60]
l[:2]
l[2:]

# s[a:b:c] can be used to specify a stride or step c, causing the resulting slice to skip items
s = 'robin'
s[::2]
s[::-1]
# produce a slice object: slice(a, b, c), Python calls seq.__getitem__(slice(start, stop, step))
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)


"\nwhy slices and range exclude the last item, work well with the zero-based indexing\n1. it's easy to see the length, range(3) and my_list[:3] both produce three items\n2. it's easy to compute the length of a slice or range when start and stop are given: just stop - start\n3. It’s easy to split a sequence in two parts at any index x, without overlapping: simply get my_list[:x] and my_list[x:].\n"

[10, 20]

[30, 40, 50, 60]

'rbn'

'nibor'

In [12]:
# multidimensional slicing and ellipsis
# a[m:n, k:l]
"""
The ellipsis—written with three full stops (...) and not … (Unicode U+2026)—is recognized
as a token by the Python parser. It is an alias to the Ellipsis object, the single
instance of the ellipsis class.2 As such, it can be passed as an argument to functions
and as part of a slice specification, as in f(a, ..., z) or a[i:...]. NumPy uses ...
as a shortcut when slicing arrays of many dimensions; for example, if x is a fourdimensional
array, x[i, ...] is a shortcut for x[i, :, :, :,]. See the Tentative
NumPy Tutorial to learn more about this.
"""
import numpy as np
arr = np.array([[1, 2], [4, 3]])
arr[1, ...]

'\nThe ellipsis—written with three full stops (...) and not … (Unicode U+2026)—is recognized\nas a token by the Python parser. It is an alias to the Ellipsis object, the single\ninstance of the ellipsis class.2 As such, it can be passed as an argument to functions\nand as part of a slice specification, as in f(a, ..., z) or a[i:...]. NumPy uses ...\nas a shortcut when slicing arrays of many dimensions; for example, if x is a fourdimensional\narray, x[i, ...] is a shortcut for x[i, :, :, :,]. See the Tentative\nNumPy Tutorial to learn more about this.\n'

array([4, 3])

In [13]:
# assigning to slices
"""
slices can also be used to change mutable sequences in place, that is, without rebuilding from scratch
"""
l = list(range(10))
l
l[2:5] = [20, 30]
l
del l[5:7]
l
# when the target of the assignment is a slice , the right side must be an iterable object


'\nslices can also be used to change mutable sequences in place, that is, without rebuilding from scratch\n'

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[0, 1, 20, 30, 5, 6, 7, 8, 9]

[0, 1, 20, 30, 5, 8, 9]

In [16]:
# using + and * with sequences
"""
+ and * not modified but a new sequence of the same type is created as result of the concatenation
"""
l = [1, 2, 3]
l * 5
"""
[[]] * 3 will result in a list with three references to the same inner list
"""
ll = [[]] * 3
ll
ll[0].append(1)
ll

'\n+ and * not modified but a new sequence of the same type is created as result of the concatenation\n'

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

'\n[[]] * 3 will result in a list with three references to the same inner list\n'

[[], [], []]

[[1], [1], [1]]

In [20]:
# building lists of lists
board = [['_'] * 3 for i in range(3)]
board
board[1][2] = 'X'
board

weird_board = [['_'] * 3] * 3
weird_board
weird_board[1][2] = '0'
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [22]:
# augmented assignment with sequences
"""
+=, *=
the special method that makes += work is __iadd__, if __iadd__ is not implemented, will falls back to calling __add__
In general, for mutable sequences, it is a good bet that __iadd__ is implemented and
that += happens in place. For immutable sequences, clearly there is no way for that to
happen.
"""
l = [1, 2, 3]
id(l)
l *= 2
id(l)
t = (1, 2, 3)
id(t)
t *= 2
id(t)
"""
str is an exception to this description. Because string building with += in loops is so common in the wild,
CPython is optimized for this use case. str instances are allocated in memory with room to spare, so that
concatenation does not require copying the whole string every time.
"""

'\n+=, *=\nthe special method that makes += work is __iadd__, if __iadd__ is not implemented, will falls back to calling __add__\nIn general, for mutable sequences, it is a good bet that __iadd__ is implemented and\nthat += happens in place. For immutable sequences, clearly there is no way for that to\nhappen.\n'

2930898699016

2930898699016

2930641757600

2930898537544

'\nstr is an exception to this description. Because string building with += in loops is so common in the wild,\nCPython is optimized for this use case. str instances are allocated in memory with room to spare, so that\nconcatenation does not require copying the whole string every time.\n'

In [24]:
# A += Assignment Puzzler
t = (1, 2, [30, 40])
t[2] += [50, 60]
t   # t becomes (1, 2, [30, 40, 50, 60]) 同时也会报错

TypeError: 'tuple' object does not support item assignment

In [26]:
"""
it's a corner case, 通过bytecode很明显的看出来list先做+=，然后赋值给tuple（产生错误，因为tuple是immutable）
three lessons:
1. putting mutable items in tuples is not a good idea
2. Augmented assignment is not an atomic operation—we just saw it throwing an exception after doing part of its job
3. Inspecting Python bytecode is not too difficult, and is often helpful to see what is going on under the hood
"""


"\nit's a corner case, 通过bytecode很明显的看出来list先做+=，然后赋值给tuple（产生错误，因为tuple是immutable）\nthree lessons:\n1. putting mutable items in tuples is not a good idea\n2. Augmented assignment is not an atomic operation—we just saw it throwing an exception after doing part of its job\n3. Inspecting Python bytecode is not too difficult, and is often helpful to see what is going on under the hood\n"

In [6]:
# list.sort and the sorted built-in function
_ = """
list.sort sorts a list in place(without making a copy), It returns
None to remind us that it changes the target object, and does not create a new list. This
is an important Python API convention: functions or methods that change an object in
place should return None to make it clear to the caller that the object itself was changed,
and no new object was created.
"""
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)
fruits
sorted(fruits, reverse=True)   # ascending by default(reverse=False)
sorted(fruits, key=len)
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

['grape', 'raspberry', 'apple', 'banana']

['raspberry', 'grape', 'banana', 'apple']

['grape', 'apple', 'banana', 'raspberry']

['apple', 'banana', 'grape', 'raspberry']

In [7]:
# managing ordered sequences with bisect
"""
bisect module offers bisect and insort
"""
# searching with bisect
_ = """
bisect(haystack, needle)
"""
import  bisect


HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]
for x in NEEDLES:
    print(bisect.bisect(HAYSTACK, x))


'\nbisect module offers bisect and insort\n'

0
1
1
3
5
5
9
11
13
14
14


In [8]:
# inserting with bisect
import bisect
import random
_ = """
insort(seq, item) inserts item into seq so as to keep seq in ascending order
"""
SIZE = 7
random.seed(1729)
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [15]:
# when a list is not the answer
_ = """
The list type is flexible and easy to use, but depending on specific requirements, there
are better options. For example, if you need to store 10 million floating-point values, an
array is much more efficient, because an array does not actually hold full-fledged float
objects, but only the packed bytes representing their machine values—just like an array
in the C language. On the other hand, if you are constantly adding and removing items
from the ends of a list as a FIFO or LIFO data structure, a deque (double-ended queue)
works faster.

If your code does a lot of containment checks (e.g., item in
my_collection), consider using a set for my_collection, especially
if it holds a large number of items. Sets are optimized for fast
membership checking. But they are not sequences (their content
is unordered). We cover them in Chapter 3.
"""
# arrays
_ = """
If the list will only contain numbers, an array.array is more efficient than a list: it
supports all mutable sequence operations (including .pop, .insert, and .extend), and
additional methods for fast loading and saving such as .frombytes and .tofile.

A Python array is as lean as a C array. When creating an array, you provide a typecode,
a letter to determine the underlying C type used to store each item in the array. For
example b is the typecode for signed char. If you create an array('b'), then each item
will be stored in a single byte and interpreted as an integer from –128 to 127. For large
sequences of numbers, this saves a lot of memory. And Python will not let you put any
number that does not match the type for the array.
"""
from array import array
from random import random


floats = array('d', (random() for i in range(10**7)))   # 'd': double-precision floats
floats[-1]
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]
floats2 == floats

# a = array.array(a.typecode, sorted(a))

0.6273988193840452

0.6273988193840452

True

In [18]:
# memory views
_ = """
The built-in memorview class is a shared-memory sequence type that lets you handle
slices of arrays without copying bytes. It was inspired by the NumPy library (which we’ll
discuss shortly in “NumPy and SciPy” on page 52). Travis Oliphant, lead author of Num‐
Py, answers When should a memoryview be used? like this:
A memoryview is essentially a generalized NumPy array structure in Python itself
(without the math). It allows you to share memory between data-structures (things like
PIL images, SQLlite databases, NumPy arrays, etc.) without first copying. This is very
important for large data sets.

memoryview.cast method lets you change the way multiple bytes are read or written as units without moving
bits around.
memoryview.cast returns yet another memoryview objext, always sharing the same memory

"""
numbers = array('h', [-2, -1, 0, 1, 2])  # 'h': short signed integers
memv = memoryview(numbers)
len(memv)
memv[0]
memv_oct = memv.cast('B')   # 'B': unsigned char
memv_oct.tolist()
memv_oct[5] = 4
numbers

5

-2

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

array('h', [-2, -1, 1024, 1, 2])

In [19]:
# numpy and scipy
_ = """
NumPy implements multidimensional,
homogeneous arrays and matrix types that hold not only numbers but
also user-defined records, and provides efficient elementwise operations

SciPy is a library, written on top of NumPy, offering many scientific computing algorithms
from linear algebra, numerical calculus, and statistics. SciPy is fast and reliable
because it leverages the widely used C and Fortran code base from the Netlib Repository.
In other words, SciPy gives scientists the best of both worlds: an interactive prompt
and high-level Python APIs, together with industrial-strength number-crunching functions
optimized in C and Fortran.
"""
import numpy

a = numpy.arange(12)
a
type(a)
a.shape
a.shape = 3, 4
a
a[2]
a[2, 1]
a[:, 1]
a.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

numpy.ndarray

(12,)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([ 8,  9, 10, 11])

9

array([1, 5, 9])

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [26]:
# deques and other queues
_ = """
.append and .pop methods make a list usable as a stack or a queue
"""
l = [1, 2, 3]
l.append(4)
l.pop(0)
l

from collections import deque
dq = deque(range(10), maxlen=10)    # maxlen sets the maximum number of items allowed in deque
dq.rotate(3)
dq
dq.rotate(-4)
dq
dq.appendleft(-1)
dq
dq.extend([11, 22, 33])
dq
dq.extendleft([10, 20, 30, 40])
dq
dq.popleft()
dq

_ = """
heapq, heqppush, heappop
"""

1

[2, 3, 4]

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

40

deque([30, 20, 10, 3, 4, 5, 6, 7, 8])